version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: micro/pg-app:v1
    container_name: pg_app
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=brick
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d brick -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
