version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pg_app:v1
    container_name: pg_app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    networks:
      - pg
  db:
    image: postgres:latest
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=brick
    restart: always
    networks:
      - pg

networks:
  pg:
    driver: bridge